### ISSUE TITLE
Checkpoint experiment directory is cleaned (all models destroyed) upon testing

### ISSUE THREAD

**Issue by lmmx** [FudanVI/FudanOCR#1]
Firstly there isn't full usage guidance for this so I'm making some assumptions based on the TextZoom repo this was adapted from, please advise if I'm better off using it differently!

To train the model I ran:

```sh
python main.py --batch_size=32 --STN --mask --exp_name louis --text_focus
```

which successfully put `checkpoint.pth` and `model_best.pth` in `checkpoints/louis/`, however when I went to test these it printed

```
Clean the old checkpoint louis
```

and then complained:

```
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/louis/checkpoint.pth'
```

...so the saved model state was destroyed by trying to test it... Am I calling it wrong somehow? I suspect this should only be done when training (not testing) a model of the same experiment name as a pre-existing one.

**Comment by JingyeChen** [comment]
Hello! I will complete the usage as soon as possible (too many things to do now...)

**Comment by JingyeChen** [comment]
"Clean the old checkpoint louis"
===
Maybe you used the same experiment name as training when testing. I have fixed that :)

**Comment by kanika02** [comment]
> Firstly there isn't full usage guidance for this so I'm making some assumptions based on the TextZoom repo this was adapted from, please advise if I'm better off using it differently!
> 
> To train the model I ran:
> 
> ```shell
> python main.py --batch_size=32 --STN --mask --exp_name louis --text_focus
> ```
> 
> which successfully put `checkpoint.pth` and `model_best.pth` in `checkpoints/louis/`, however when I went to test these it printed
> 
> ```
> Clean the old checkpoint louis
> ```
> 
> and then complained:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/louis/checkpoint.pth'
> ```
> 
> ...so the saved model state was destroyed by trying to test it... Am I calling it wrong somehow? I suspect this should only be done when training (not testing) a model of the same experiment name as a pre-existing one.






Hey ! I am facing the difficulty to resume the epochs can you help me with that? used the command --resume and also given the path still it is starting from the start epochs only. help me solve this issue please it will be really helpful for me thanku
