### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1024 and 8192 (The offending index is 0)

### ISSUE THREAD

**Issue by kanika02** [FudanVI/FudanOCR#14]
![image](https://user-images.githubusercontent.com/35134378/134764603-d9860046-3274-4400-b0f8-d9927177f1c3.png)

Would you please help me solve this error? I don't understand what I am doing wrong.

**Comment by JingyeChen** [comment]
The bug has been fixed in the latest commit. You can have a try.

**Comment by kanika02** [comment]
Thank you so much ,it helps a  lot
