### ISSUE TITLE
super resolution.py

### ISSUE THREAD

**Issue by kanika02** [FudanVI/FudanOCR#16]
![image](https://user-images.githubusercontent.com/35134378/135213751-022030d4-29f7-4ccd-9f86-1d4718701516.png)

Do we have to change these paths ( folder_GT and folder_GN)in super_resolution.py?

Also, can we find the PSNR and SSIM of all images and store them in a CSV? How to do that?

**Comment by JingyeChen** [comment]
By the way, where does the code that you show locate? Is that written by you? I did not find it in super_resolution.py.

**Comment by JingyeChen** [comment]
You do not need to modify the path :D

**Comment by JingyeChen** [comment]
Just modify several code in the function "calculate_psnr" and "calculate_ssim" to store the results in the file
