### ISSUE TITLE
About the printed artistic dataset

### ISSUE THREAD

**Issue by hyh-dev** [FudanVI/FudanOCR#21]
Hi, can you release the printed artistic characters dataset? Or where can I download these font files?

**Comment by JingyeChen** [comment]
We will get it available within one week :D
So please remind me if I forget this XD (lots of ddl....)

**Comment by hyh-dev** [comment]
Thanks a lot!

**Comment by JingyeChen** [comment]
We have uploaded the dataset. Please see readme.md

If you find this repo useful, don't forget to leave a star :D
