### ISSUE TITLE
TBSRN链接失效

### ISSUE THREAD

**Issue by wizardlancet** [FudanVI/FudanOCR#23]
google drive上TBSRN链接可能失效了

**Comment by JingyeChen** [comment]
谢谢提醒，我们会尽快更新链接 :D

**Comment by JingyeChen** [comment]
我们上传了新的链接
https://drive.google.com/file/d/1a-BNCC1pFczz4AkY8sJatg3GpeX1MCCr/view

感谢您的提醒！

**Comment by esravar** [comment]
Is this pretrained checkpoint with stroke? (TBSRN-Stroke)
