### ISSUE TITLE
About weight_cross_entropy

### ISSUE THREAD

**Issue by terryoo** [FudanVI/FudanOCR#3]
This paper is quite impressive research.

I have a question about implementation. 

In this paper,  weight cross-entropy (Content-Aware Module) is employed for calculating loss between the prediction of SR image and gt. However, the code seems to calculate loss between the prediction of HR image and gt. https://github.com/FudanVI/FudanOCR/blob/342eb1c79ed23abe2ed944a28d7361adacf693af/scene-text-telescope/loss/text_focus_loss.py#L97

**Comment by JingyeChen** [comment]
:D Thank you for pointing out this problem.
We reconstruct the code after this paper was accepted, but have not tested the code since it is a little bit busy these days. I have fixed that problem :D
