### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\tmp\\build\\80754af9\\cffi_1613246439577\\work'

### ISSUE THREAD

**Issue by yujiajun13** [FudanVI/FudanOCR#4]
When I exec the command "pip install -r requement.txt", this error is occur

**Comment by JingyeChen** [comment]
Hello :D 
Maybe you should manually create this directory "'C:\\tmp\\build\\80754af9\\cffi_1613246439577\\work'"
