### ISSUE TITLE
lmdb.Error: ./data/mydata/train_data.mdb: Not a directory

### ISSUE THREAD

**Issue by cptbtptp125** [FudanVI/FudanOCR#48]
Hello, my experiment has been this error， lmdb.Error: ./data/mydata/train_data.mdb: Not a directory. Have you ever come across such a situation? How can I solve it? I would appreciate it if you could help me.

**Comment by zhangqiqi1228** [comment]
> 

@cptbtptp125 The input data path should be a folder rather than the mdb file. You can try ./data/mydata/train1
