### ISSUE TITLE
Where can I get files named 'train_1000' and 'test_1000'？

### ISSUE THREAD

**Issue by yeahQing** [FudanVI/FudanOCR#5]
I don`t understand why I should use split().
```python
for dataset_root in config['train_dataset'].split(',')
```

**Comment by yeahQing** [comment]
How can I create a lmdb dataset for Chinese character?

**Comment by JingyeChen** [comment]
The link of the dataset is shown in http://www.nlpr.ia.ac.cn/databases/handwriting/Home.html

**Comment by yeahQing** [comment]
> The link of the dataset is shown in http://www.nlpr.ia.ac.cn/databases/handwriting/Home.html

Hi, Chen, thanks for your reply. I have downloaded the dataset, but I don’t understand why a string is looped here. The code is:
```python
def get_data_package():
    train_dataset = []
    # 'train_dataset': './data/mydata/train_1000' why loop this path?
    for dataset_root in config['train_dataset'].split(','):
        _, dataset = get_dataloader(dataset_root, shuffle=True)
        train_dataset.append(dataset)
```

**Comment by yeahQing** [comment]
What type of data set should I replace the path **'./data/mydata/train_1000'**?

**Comment by JingyeChen** [comment]
> > The link of the dataset is shown in http://www.nlpr.ia.ac.cn/databases/handwriting/Home.html
> 
> Hi, Chen, thanks for your reply. I have downloaded the dataset, but I don’t understand why a string is looped here. The code is:
> 
> ```python
> def get_data_package():
>     train_dataset = []
>     # 'train_dataset': './data/mydata/train_1000' why loop this path?
>     for dataset_root in config['train_dataset'].split(','):
>         _, dataset = get_dataloader(dataset_root, shuffle=True)
>         train_dataset.append(dataset)
> ```

A loop is used to concatenate multiple datasets. For example, the dataset can be formulated in this way:

'train_dataset': './data/mydata/train_1000,./data/mydata/train_1500,./data/mydata/train_2000'

**Comment by JingyeChen** [comment]
> What type of data set should I replace the path **'./data/mydata/train_1000'**?

The format should be lmdb

**Comment by yeahQing** [comment]
Thank you very much, it has helped me a lot!

**Comment by cptbtptp125** [comment]
Hello, have you successfully converted LMDB format? I want to know how to convert, I have tried many methods without success

**Comment by cptbtptp125** [comment]
Hello, I am a little confused about the loop connection of multiple data sets, may I ask why this operation is carried out, and what is the difference between it and the direct single training? Thank you very much for your reply. I would appreciate it if you could help me.
'train_dataset': './data/mydata/train_1000,./data/mydata/train_1500,./data/mydata/train_2000'
