### ISSUE TITLE
what is exp_name？

### ISSUE THREAD

**Issue by Lz-2019317** [FudanVI/FudanOCR#6]

**Comment by JingyeChen** [comment]
exp_name denotes the name of your experiment. 
For example, you can name your experiment with "【0813】MyFirstExperiment" or "【0813】TBSRN" ....
Then a folder named exp_name will be automatically created containing checkpoints and some logs :D

**Comment by Lz-2019317** [comment]
Thank you very much，i got it.

**Comment by Lz-2019317** [comment]
Thank you.
If we try to replace self-attention module in the TSRN by the other attention module,the performance of SR will be better?
If we use&nbsp; multi-scaled feature extract module in the CNN stage ,the performance of SR will be better?
&nbsp;
thank you very much~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FudanVI/FudanOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FudanVI/FudanOCR] what is exp_name？ (#6)





 
exp_name denotes the name of your experiment.
 For example, you can name your experiment with "【0813】MyFirstExperiment" or "【0813】TBSRN" ....
 Then a folder named exp_name will be automatically created containing checkpoints and some logs :D
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JingyeChen** [comment]
It is an interesting question. I suppose you can have a try :D

The original self-attention used in TBSRN is simply inspired by vanilla Transformer. I guess the performance (or efficiency) can be boosted further with improved attention modules.
