### ISSUE TITLE
Question about CLIP-like pre-training in image-ids-CTR

### ISSUE THREAD

**Issue by ZZXF11** [FudanVI/FudanOCR#75]
Thanks for your great job on Chinese Text Recognization in ICCV 2023. But we have some questions that, during the CCR-CLIP Pre-training Stage, how many characters are chosen for pre-trainin during zero-shot setting of HWDB? Because if the number of your pre-training characters is larger than `m`, it is an unfair comparison with other methods.

**Comment by hyangyu** [comment]
In the zero-shot settings, we use the same training set as the previous methods.
