### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by leez20** [FudanVI/FudanOCR#78]
VCTR数据集下载链接跳转不了

**Comment by hyangyu** [comment]
数据集链接: https://pan.baidu.com/s/1CApS3pDResDxN-kCJraplw  密码: 07ka

**Comment by Apostatee** [comment]
> 数据集链接: https://pan.baidu.com/s/1CApS3pDResDxN-kCJraplw 密码: 07ka

该数据集解析到 第4085张出现段错误，可否再提供一下没有问题的数据集
