### ISSUE TITLE
请问在竖直文本识别那篇论文中，有没有提供预训练模型呢

### ISSUE THREAD

**Issue by bucaiLi** [FudanVI/FudanOCR#81]
rt，除此之外，为什么我下载的benchmark_new.txt是乱码的，这个文件是要怎么使用。。

**Comment by hyangyu** [comment]
该文件是数据集的字符集合，下载乱码可能是您本地问题呢，我这里查看是没有问题的。预训练模型整理后会更新。

**Comment by bucaiLi** [comment]
> 该文件是数据集的字符集合，下载乱码可能是您本地问题呢，我这里查看是没有问题的。预训练模型整理后会更新。

好的好的 感谢老哥回复！！
