### ISSUE TITLE
CCR-CLIP使用印刷字体进行增强

### ISSUE THREAD

**Issue by AnatoleWang** [FudanVI/FudanOCR#87]
您好，在论文里有提到，可以使用印刷体参与训练，可以很大程度提升zero-shot测试的精度。根据引用的文献，手写体和印刷体经过网络后，得到的特征直接进行矩阵相乘，而在您的代码里，手写体特征和部件拆分特征，同样进行的是矩阵乘法。如果想把这两种方法融合起来，请问是进行何种操作，获得更高的zero-shot accuracy的呢？我暂未看到这部分的源码，期待您的回复，谢谢！

**Comment by hyangyu** [comment]
您好~ 论文中提到的印刷体参与训练指的是先用印刷体字符对模型进行预训练，然后在预训练参数上再用手写数据集进行微调。
