### ISSUE TITLE
How to download pretrained model without Baidu account?

### ISSUE THREAD

**Issue by abghaky** [FudanVI/FudanOCR#99]
I am having a hard time downloading the pretrained models. I am not located in China and cannot download them on Baidu. Is there any alternative way?

**Comment by hyangyu** [comment]
Which one?  I can upload it into Google Drive.

**Comment by abghaky** [comment]
Thanks for the replay. I need the pretrained weights for "Text Gestalt: Stroke-Aware Scene Text Image Super-Resolution" and "Scene Text Telescope: Text-Focused Scene Image Super-Resolution" papers.
